# Generated by Django 5.0.7 on 2024-07-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cus_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='cus_ph',
            new_name='customer_phone_number',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='event_name',
        ),
    ]
